services:
  postgres:
    image: postgres:16-alpine
    container_name: erin-greeter-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-user_service}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-user_service}"]
      interval: 5s
      timeout: 3s
      retries: 10

  liquibase:
    image: liquibase/liquibase:4.27
    container_name: erin-greeter-liquibase
    depends_on:
      - postgres
    volumes:
      - ./user-service/liquibase:/liquibase/changelog:ro

volumes:
  pgdata:
