import { Generated } from 'kysely';

export interface UserTable {
  id: string; // UUID provided from message (not generated)
  first_name: string;
  last_name?: string;
  birthday?: string;
  created_at: Generated<Date>; // Generated by database (now())
  timezone: string;
}
export interface Database {
  user: UserTable;
}