services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=aws-auth,sqs,secretsmanager,rds,ec2,iam,cloudformation,sts,ssm,lambda,apigateway,cloudwatchlogs,events
      - DEBUG=1
      - EAGER_SERVICE_LOADING=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - RDS_ENGINE=postgres
      - RDS_FEATURES=custom_resources
      - DEBUG=1
      - LOCALSTACK_HOST=localhost
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - PERSISTENCE=1
      - START_WEB=0
      - SKIP_SSL_CERT_DOWNLOAD=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-data:/var/lib/localstack"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s