services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    extra_hosts:
      - "secretsmanager.us-east-1.amazonaws.com:host-gateway"  
    environment:
      - SERVICES=aws-auth,sqs,secretsmanager,rds,ec2,iam,cloudformation,sts,ssm,lambda,apigateway,cloudwatchlogs,events,logs
      - DEBUG=1
      - EAGER_SERVICE_LOADING=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - RDS_ENGINE=postgres
      - RDS_FEATURES=custom_resources
      - LS_LOG=trace
      - LOCALSTACK_HOST=localhost
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - PERSISTENCE=1
      - START_WEB=0
      - SKIP_SSL_CERT_DOWNLOAD=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-data:/var/lib/localstack"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  postgres:
    image: postgres:16-alpine
    container_name: rds-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-test} -d ${POSTGRES_DB:-postgres}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
